# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

############################
## Theme
############################

# Choose a theme.
#   Latest themes (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in themes in `themes/academic/data/themes/`
#   Browse user installed themes in `data/themes/`
[appearance]
theme_day = "minimal"

# Enable users to switch between day and night mode?
theme_night = "minimal"

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = "minimal"

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "M"

############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization

############################
## Site Features
############################

[features.syntax_highlighter]
# Enable source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
theme_light = "pygments"
theme_dark = "native"

# Enable LaTeX math rendering? true/false
#   If false, you can enable math on a per page basis as needed.
[features.math]
enable = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
[features.privacy_pack]
enable = false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
[features.repository]
url = "https://github.com/yewton/yewton.net"
content_dir = "content"
branch = "master"

# Get user avatars from Gravatar.com? (true/false)
[features.avatar]
gravatar = true
shape = "circle"

############################
## Comments
############################
[features.comment]
# Comment provider:
#   0: Disabled
#   1: Disqus (https://disqus.com)
#   2: Commento (https://commento.io)
provider = "disqus"

# Configuration of Disqus.
[features.comment.disqus]
shortname = "yewton"  # Paste the shortname from your Disqus dashboard.
show_count = false  # Show comment count in page header? (true/false)

# Configuration of Commento.
[features.comment.commento]
# If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.
url = ""

############################
## Search
############################
[features.search]
# Search provider:
#   0: No search engine
#   1: Academic (built-in)
#   2: Algolia (https://www.algolia.com)
provider = "wowchemy"

# Configuration of Algolia search engine.
# Paste the values from your Algolia dashboard.
[features.search.algolia]
app_id = ""
api_key = ""
index_name = ""
show_logo = false

############################
## Maps
############################
[features.map]
# To show your address on a map in the Contact widget, enter your latitude and longitude (above)
# and choose a map provider below.
#
# To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
#   https://developers.google.com/maps/documentation/javascript/get-api-key
# To use OpenStreetMap tiles, set `engine` to 2.
# To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
#   https://www.mapbox.com/studio/account/tokens
#
# Map provider:
#   0: No map
#   1: Google Maps
#   2: OpenStreetMap (Mapnik)
#   3: OpenStreetMap (Mapbox)
provider = ""
api_key = ""
zoom = 15

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
[locale]
date_format = "2006年1月2日"
#   Examples: "3:04 pm" or "15:04"
time_format = "3:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-us"

############################
## Advanced
############################

# Main menu alignment (l = left, c = center, r = right) and logo options.
[header.navbar]
align = "l"
show_logo = true

[footer.copyright]
# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
notice = "© 2016-{year} yewton"

############################
## Marketing
############################
[marketing.seo]
site_type = "Person"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = ""

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = ""

# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = "yewton"

[marketing.analytics]
google_analytics = "UA-72312909-1"
#  google_tag_manager = "GTM-WRWPP44"

[marketing.verification]
google = ""
baidu = ""

# PLACE THIS NEW [CMS] CONFIG SECTION AT THE END OF THE FILE

# Content Management System
[extensions.cms]
# Enable the admin panel. See https://wowchemy.com/docs/install/
branch = "master"
local_backend = false

# Icon Pack Extensions
[extensions.academicons]
enable = true  # Enable the Academicons icon pack https://jpswalsh.github.io/academicons/
