hugoblox:
  locale:
    date_format: "2006年1月2日"
    time_format: "3:04 PM"
    address_format: en-us
  identity:
    type: Person
    social:
      twitter: yewton
  copyright:
    notice: "© 2016-{year} yewton"
  layout:
    avatar_shape: circle
  comments:
    provider: disqus
    disqus:
      shortname: yewton
  header:
    align: l
  content:
    math:
      enable: false
  analytics:
    google:
      measurement_id: "G-SJ7FG3D0T4"
