# SITE SETUP
appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: M

features:
  syntax_highlighter:
    theme_light: pygments
    theme_dark: native
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/yewton/yewton.net"
    content_dir: content
    branch: master
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: disqus
    disqus:
      shortname: yewton
      show_count: false
  search:
    provider: hugoblox
  map:
    provider: ""

locale:
  date_format: "2006年1月2日"
  time_format: "3:04 PM"
  address_format: en-us

header:
  navbar:
    align: l
    show_logo: true

footer:
  copyright:
    notice: "© 2016-{year} yewton"

marketing:
  seo:
    site_type: Person
    twitter: yewton
  analytics:
    google_analytics: "G-SJ7FG3D0T4"

extensions:
  academicons:
    enable: true
