#+setupfile: setup.org
#+hugo_section: post
#+seq_todo: TODO DRAFT DONE

* 雑記                                                             :@雑記:
:PROPERTIES:
:END:

** DONE 久々の更新                                      :emacs:hugo:ox_hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_BUNDLE: 2020-01-02_happy_new_year
:EXPORT_HUGO_SLUG: happy-new-year
:EXPORT_DATE: 2019-01-02
:END:

最近仕事用のmacを新調して環境を作り直す機会があったことと、 2020 年が始まるということもあり、久々にサイトを更新することにした。

[[/cv/][オープン職務経歴書]]を書きたかった、というのもある。

更新にあたっていくつか困難があった。

*まず、このサイトのソースが最近の Hugo では動かせなくなっていた。*

このサイトのテーマには [[https://github.com/digitalcraftsman/hugo-icarus-theme][Icarus]] を使わせていただいているのだが、最終更新が 2017 年となっており、
Hugo 0.55.0 以降で動かなくなってしまっていたり、 Deprecated Warning が出るようになっていた。

[[https://github.com/digitalcraftsman/hugo-icarus-theme/pull/124][PRは出されている]] のだけれど、マージされる様子が無い。

そもそも、当時のバージョンに対してカスタマイズしたレイアウトを作ってしまったので、
単純なテーマの更新だけでは追随できない。

どのバージョンなら動くのか突き止めるのも骨が折れた。
[[https://bitbucket.org/mgladdish/asdf-gohugo][asdf-gohugo]] を入れて、少しずつバージョンを上げながら確認していった。

#+begin_src sh
asdf plugin add hugo https://bitbucket.org/mgladdish/asdf-gohugo
#+end_src

*そして、そもそも Hugo の使い方を忘れていた。*

[[/2016/02/02/blog-with-hugo/][Hugo 導入記事]] や [[/2016/01/26/hugo-el/][Hugo 用 Emacs ライブラリ]] を書いておいてなんだが、当時から3年も経ってほとんど忘れてしまっていた。

そこで改めて調べてみると、イマドキは org-mode で書くことも出来るらしい。

この3年ですっかり org-mode 無しでは生きられない体になってしまっていたし、
せっかくなので本記事からは [[https://ox-hugo.scripter.co/][ox-hugo]] を使って書くことにする。

使い始めるにあたって色々調べたり考えたりすることも多かったので、そのうち記事にしようと思う。
結論としては、org-mode と Hugo の組み合わせは最高だし、その橋渡しをしてくれる [[https://ox-hugo.scripter.co/][ox-hugo]] は本当にグッジョブだということ。

...

そんなこんなで色々対応していたものの、デプロイする仕組みなどは当時と変わりなく動いたのでその点は助かった。

org-mode で書けるようになったことだし、少しは記事を書いていきたい所だが、まずは Hugo の最新版に追従する作業が待っている…。

** DONE #MadeWithAcademic                                 :academic:ox_hugo:
:PROPERTIES:
:EXPORT_HUGO_BUNDLE: 2020-01-06_academic
:EXPORT_HUGO_SLUG: made-with-academic
:EXPORT_FILE_NAME: index
:EXPORT_DATE: 2019-01-06
:END:

[[https://github.com/digitalcraftsman/hugo-icarus-theme][Icarus]] がメンテされておらず Hugo 0.55.0 以降で正しく動かなくなっていたので、
自力で Icarus にパッチを充てるか、別のテーマに乗り換えるかという選択を迫られていた。

せっかくなのでランディングページとブログを別にしたかったので、そういう柔軟性を備えている
[[https://sourcethemes.com/academic/][Academic]] というテーマを使うことにした。

テーマの変更にあたって様々な知見が得られたので、そのうち記事にしたい。

以下その候補:

- [[https://gohugo.io/content-management/page-bundles/][Page Bundles]] への移行
- [[https://ox-hugo.scripter.co/doc/why-ox-hugo/][ox-hugo]] と Academic が如何に相性がよいか
  - auto weight あたりが最高
  - =lastmod= の自動更新や [[https://ox-hugo.scripter.co/doc/custom-front-matter/#front-matter-extra][Front-matter Extra]] は Academic じゃなても最高の体験
- カスタムウィジェットの作り方
- ダークテーマ対応のシンタックスハイライトのやりかた
- conf-toml-mode を [[https://ox-hugo.scripter.co/doc/custom-front-matter/#front-matter-extra][Front-matter Extra]] で使う方法

** DRAFT 久々の更新2                                    :emacs:hugo:ox_hugo:
:PROPERTIES:
:EXPORT_FILE_NAME: index
:EXPORT_HUGO_BUNDLE: 2020-01-05_random
:EXPORT_HUGO_SLUG: random
:EXPORT_DATE: 2019-01-05
:END:

org-mode ではタグにハイフンを付けられない。

=ox_hugo= ~hoge~

conf-toml がある https://github.com/dryman/toml-mode.el/issues/14

#+begin_src emacs-lisp
(use-package ox-hugo
  :after ox
  :init
  (defalias 'toml-mode 'conf-toml-mode)
  :config 
  (setq org-hugo-use-code-for-kbd t))
#+end_src

#+begin_src sh
hugo gen chromastyles --style=monokai > pbcopy
hugo gen chromastyles --style=monokailight > pbcopy
#+end_src

https://css2sass.herokuapp.com/

=.np= とか、light にしか無いやつを消した(暫定)

https://gohugo.io/getting-started/configuration-markup#highlight

#+begin_src toml
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "emacs"
    tabWidth = 4
#+end_src

https://github.com/sourcethemes/academic-scripts に page bunlde 化するスクリプトがある。

#+begin_src sh
asdf plugin add hugo https://github.com/beardix/asdf-hugo
#+end_src

=baseurl= を設定しないと Twitter Card などが表示されないので気をつけよう

#+begin_src toml
# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://www.yewton.net/"
#+end_src

=google_tag_manager= が設定されていると Google Analytics のコードが埋め込まれない
https://spectrum.chat/academic/help/google-analytics-not-working-for-me~3e802803-663f-4b38-8d6f-bc645935da26?authed=true




