#+setupfile: setup.org
#+hugo_section: cv
#+hugo_front_matter_key_replace: title>nil author>nil draft>nil

* index
:PROPERTIES:
:EXPORT_FILE_NAME: index
:END:

#+begin_src toml :front_matter_extra t
type = "widget_page"
#+end_src

* cv
:PROPERTIES:
:EXPORT_HUGO_WEIGHT: auto
:END:

** about
:PROPERTIES:
:EXPORT_FILE_NAME: about
:END:

#+begin_src toml :front_matter_extra t
  # About widget.
  widget = "about-ext"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "人となり"

  # Choose the user profile to display
  # This should be the username of a profile in your `content/authors/` folder.
  # See https://sourcethemes.com/academic/docs/get-started/#introduce-yourself
  author = "admin"
#+end_src

** programming language skills
:PROPERTIES:
:EXPORT_FILE_NAME: pl_skills
:END:

#+begin_src toml :front_matter_extra t
  # A Skills section created with the Featurette widget.
  widget = "featurette-l"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "プログラミング言語"

  # Showcase personal skills or business features.
  # 
  # Add/remove as many `[[feature]]` blocks below as you like.
  # 
  # For available icons, see: https://sourcethemes.com/academic/docs/widgets/#icons

  [feature]
    icon = "code"
    icon_pack = "fas"
    description = "※2020年1月時点"
#+end_src

| 名称        | 業務経験 | レベル感                                                                          |
|-------------+----------+-----------------------------------------------------------------------------------|
| Ruby        | 5年      | RoR アプリを一人で開発出来るし、指導もできる                                  |
| JavaScript  | 2年      | React で基本的な実装や Lambda で Node.js の適当な機能は作れる                     |
| Objective-C | 2年      | 一人で開発は進められるけれどそんなに自信は無い                                    |
| Swift       | 2年      | 同上                                                                              |
| Kotlin      | 2年      | Android に関しては同上。サーバーサイドに関しては Spring Boot でそこそこ出来るはず |
| Java        | 2年      | Lambda や Stream を使ってテストも書きつつ一人で Spring Boot 開発出来る            |
| Scala       | 2年      | Play! で基本的には一人で開発出来る。Scalazとかは怪しい                            |
| Python      | 2年      | Fabric 等で薄く触ってる程度                                                       |
| PHP         | 5年      | PHP 6 の時代まで。もう忘れた                                                      |
| Emacs Lisp  | 10年     | https://github.com/yewton/.emacs.d を見てください                                 |

** middleware skills
:PROPERTIES:
:EXPORT_FILE_NAME: mw_skills
:END:

#+begin_src toml :front_matter_extra t
  # A Skills section created with the Featurette widget.
  widget = "featurette-l"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "ミドルウェア"

  # Showcase personal skills or business features.
  # 
  # Add/remove as many `[[feature]]` blocks below as you like.
  # 
  # For available icons, see: https://sourcethemes.com/academic/docs/widgets/#icons

  [feature]
    icon = "database"
    icon_pack = "fas"
    description = "※2020年1月時点"
#+end_src

| 名称           | 業務経験 | レベル感                                                                                                                                           |
|----------------+----------+----------------------------------------------------------------------------------------------------------------------------------------------------|
| MySQL(MariaDB) | 10年     | レプリケーションやらバックアップやらの一通りの運用や基本的なパフォーマンスチューニングは出来る。変わったところだと Galera クラスターの運用経験有り |
| PostgreSQL     | 2年      | Heroku についてるのである程度触れる程度                                                                                                            |
| Redis          | 5年      | キャッシュとして当たり前に運用する程度                                                                                                             |
| Elasticsearch  | 2年      | 日本語インクリメンタルサーチや表記揺れの対応が出来る程度                                                                                           |
| Docker         | 5年      | 基本的には日々の開発で使うのみ。一部本番サービスでも運用したが堅牢性が求められるようなクリティカルな利用経験は無い                                 |

** cloud skills
:PROPERTIES:
:EXPORT_FILE_NAME: cloud_skills
:END:

#+begin_src toml :front_matter_extra t
  # A Skills section created with the Featurette widget.
  widget = "featurette-l"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "クラウド"

  # Showcase personal skills or business features.
  # 
  # Add/remove as many `[[feature]]` blocks below as you like.
  # 
  # For available icons, see: https://sourcethemes.com/academic/docs/widgets/#icons

  [feature]
    icon = "cloud"
    icon_pack = "fas"
    description = "※2020年1月時点"
#+end_src

| 名称 | 業務経験 | レベル感                                                              |
|------+----------+-----------------------------------------------------------------------|
| AWS  | 5年      | Webアプリ開発に必要な一通りは運用経験有り。サーバーレスとかはあんまり |
| GCP  | 2年      | BigQuery とか Vision API とかの単機能をたまに利用する程度             |

** experience
:PROPERTIES:
:EXPORT_FILE_NAME: experience
:END:

#+begin_src toml :front_matter_extra t
  # Experience widget.
  widget = "experience"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "職務要約"
  subtitle = ""

  # Date format for experience
  #   Refer to https://sourcethemes.com/academic/docs/customization/#date-format
  date_format = "2006年1月"

  # Experiences.
  #   Add/remove as many `[[experience]]` blocks below as you like.
  #   Required fields are `title`, `company`, and `date_start`.
  #   Leave `date_end` empty if it's your current employer.
  #   Begin/end multi-line descriptions with 3 quotes `"""`.


  [[experience]]
    title = "入社"
    company = "株式会社D"
    date_start = "2010-04-01"
    date_end = "2010-07-01"
    description = "PHPによるシステム開発研修を受講"

  [[experience]]
    title = "テレビ実況システムバックエンド開発"
    company = "株式会社D"
    date_start = "2010-07-01"
    date_end = "2010-08-01"
    description = "PHP (独自フレームワーク) 製。メンバーとして参加"

  [[experience]]
    title = "ニュースサイト開発"
    company = "株式会社D"
    date_start = "2010-08-01"
    date_end = "2011-11-01"
    description = "PHP (独自フレームワーク) 製。メンバーとして参加"

  [[experience]]
    title = "動画投稿・変換システム開発"
    company = "株式会社D"
    date_start = "2011-11-01"
    date_end = "2013-12-01"
    description = "PHP (ノンフレームワーク) 製。メンバーとして参加し、2012年5月以降は開発リーダーを務める"

  [[experience]]
    title = "PUSH 通知システム開発"
    company = "株式会社D"
    date_start = "2013-12-01"
    date_end = "2015-09-01"
    description = "Play! Scala 製。プロジェクトリーダーとして参加"

  [[experience]]
    title = "システム間連携システム開発"
    company = "株式会社D"
    date_start = "2014-11-01"
    date_end = "2015-09-01"
    description = "Play! Scala 製。プロジェクトリーダーとして参加"

  [[experience]]
    title = "PUSH 通知・システム間連携システム課"
    company = "株式会社D"
    date_start = "2015-02-01"
    date_end = "2015-09-01"
    description = "課長に就任。メンバーのマネジメントを行なう"

  [[experience]]
    title = "レシピ閲覧サイトバックエンド開発"
    company = "株式会社R"
    date_start = "2015-09-01"
    date_end = ""
    description = "Ruby on Rails 製。開発メンバーとして参加。2017年4月以降はiOS、Android アプリのエンハンス開発も担当"

  [[experience]]
    title = "学生向け学習時間管理支援システムバックエンド開発"
    company = "株式会社R"
    date_start = "2018-01-01"
    date_end = "2018-04-01"
    description = "Ruby on Rails 製。開発メンバーとして参加。"

  [[experience]]
    title = "マッチングサービス開発"
    company = "株式会社R"
    date_start = "2018-04-01"
    date_end = "2019-04-01"
    description = "Spring Boot 製。スクラムマスター。2018年9月以降はテックリードとして技術課題の解消に注力"

  [[experience]]
    title = "挙式支援サービスiOS開発"
    company = "株式会社R"
    date_start = "2019-04-01"
    date_end = ""
    description = "開発メンバーとして参加"

  [[experience]]
    title = "個人事業主として開業"
    company = "YAGNI ワーク"
    date_start = "2017-10-01"
    date_end = ""
    description = """
  知り合いから声を掛けられて副業を開始。
  その頃ちょうど `.work` ドメインが安売りされていて [yagni.work](https://yagni.work) というドメインを安く取れたので、
  屋号を YAGNI ワークとした。
  """

  [[experience]]
    title = "BtoB動画マニュアル管理ツール開発"
    company = "株式会社S"
    date_start = "2017-10-01"
    date_end = ""
    description = "Ruby on Rails 製。個人事業主として開発全般の業務委託を請け負う"
#+end_src

** accomplishments
:PROPERTIES:
:EXPORT_FILE_NAME: accomplishments
:END:

#+begin_src toml :front_matter_extra t
  # Accomplishments widget.
  widget = "accomplishments"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "資格など"
  subtitle = ""

  # Date format
  #   Refer to https://sourcethemes.com/academic/docs/customization/#date-format
  date_format = "2006-01-02"

  # Accomplishments.
  #   Add/remove as many `[[item]]` blocks below as you like.
  #   `title`, `organization` and `date_start` are the required parameters.
  #   Leave other parameters empty if not required.
  #   Begin/end multi-line descriptions with 3 quotes `"""`.

  [[item]]
    organization = "Scrum Alliance"
    organization_url = "https://www.scrumalliance.org/"
    title = "Certified ScrumMaster®"
    url = "https://www.scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster"
    certificate_url = "https://www.scrumalliance.org/community/profile/ysasaki"
    date_start = "2015-11-16"
    date_end = "2017-11-16"
    description = "更新はしてないです…"
#+end_src

** topics
:PROPERTIES:
:EXPORT_FILE_NAME: topics
:END:

#+begin_src toml :front_matter_extra t
  # Accomplishments widget.
  widget = "blank"  # See https://sourcethemes.com/academic/docs/page-builder/
  headless = true  # This file represents a page section.
  active = true  # Activate this widget? true/false

  title = "トピック"
  subtitle = ""

  [design]
    # Choose how many columns the section has. Valid values: 1 or 2.
    columns = "1"
#+end_src

*** 動画サムネイルシークの開発

各時点のサムネイルを選んでシークするという機能を、バックエンドからフロントエンドまで全て一人で対応した。

FFmpeg のシーンチェンジ検出結果を保存、配信し、それをネイティブクライアントが利用してシークする、というもの。

ネイティブ開発は初めてだったが、3ヶ月程で Android, iOS ともに対応することが出来た。

*ひとつの機能をバックエンドからフロントエンドまで一気通貫で全て独力で実装する* という貴重な経験だった。

*** メディアコンテンツ投稿・変換・配信システムのエンハンス開発

S3 にファイルを直接アップロードすることによる負荷軽減や、 [[https://www.imgix.com/][imgix]] と連携した画像配信、
複数ファイルの非同期並列アップロード対応などのエンハンスを行った。

素の JS のままでは並列的な処理を書くのがしんどかったため、 React でリライトした。

それまで単一ファイルのみ受け付けていたものを複数対応させるには Rails モデルのリアーキテクトも必要だった。
無停止で機能をリリースするため、事前に用意した新たなデータ構造に徐々に移行するという段取りを立て、実行を主導した。

*** Keen IO -> BigQuery 連携

[[https://keen.io/][Keen IO]] がそれまで提供していた BigQuery 連携機能を停止してしまったため(ベータとして提供されていたので仕方ない)、急遽対応したもの。

Keen が S3 にローデータを配置するのをトリガーとして Lambda を起動、 BigQuery にデータを連携する、というもの。 [[https://www.npmjs.com/package/node-lambda][node-lambda]] を用いて実装した。

突発対応で急拵えだったが特に問題なく稼動し、ことなきを得た。

自分の中の技術の引き出しを増やすいい経験だった。

*** Grape + OpenAPI による高速開発推進

3ヶ月で開発を完了させなければならず、極力無駄を省くために、 [[https://github.com/ruby-grape/grape-entity][Grape::Entity]] と [[https://github.com/ruby-grape/grape-swagger][grape-swagger]] を採用し、実装と同時に API 定義を生成し、
クライアント側はその定義を元にライブラリを自動生成して実装を進める、というアプローチで開発を進めた。

結果として上手くいき、無事に期間内にサービスインすることが出来た。

Open API を活用する好事例だった。

*** 完全なプログラミング勉強会

シニア的な立場になってきたころ、全員の「よいコード」の認識を揃えるべく、 [[https://amzn.to/35lI48z][CODE COMPLETE]] を題材にした勉強会を行なった。
そのときの資料は今でも指針として利用されている。

持ちネタとして活用出来ている。

/(今は社内限な感じになってしまっているので、無難な内容にしてそのうち一般公開したい)/
