#+setupfile: setup.org
#+hugo_section: authors/admin
#+hugo_front_matter_key_replace: title>nil author>nil draft>nil

* profile
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_FRONT_MATTER_FORMAT: yaml
:END:

#+begin_src yaml :front_matter_extra t
# Display name
title: yewton

# Username (this should match the folder name)
authors:
- admin

# Is this the primary user of the site?
superuser: true

# Role/position
role: ソフトウェアエンジニア

# Organizations/Affiliations
# organizations:
# - name: Stanford University
#   url: ""

# Short bio (displayed in user profile at end of posts)
bio: 父親兼エンジニア

# interests:
# - Emacs
# 
# education:
#   courses:
#   - course: PhD in Artificial Intelligence
#     institution: Stanford University
#     year: 2012
#   - course: MEng in Artificial Intelligence
#     institution: Massachusetts Institute of Technology
#     year: 2009
#   - course: BSc in Artificial Intelligence
#     institution: Massachusetts Institute of Technology
#     year: 2008
# 
# Social/Academic Networking
# For available icons, see: https://sourcethemes.com/academic/docs/page-builder/#icons
#   For an email link, use "fas" icon pack, "envelope" icon, and a link in the
#   form "mailto:your-email@example.com" or "#contact" for contact widget.
social:
- icon: github
  icon_pack: fab
  link: https://github.com/yewton
  display:
    header: true
- icon: twitter
  icon_pack: fab
  link: https://twitter.com/yewton
  display:
    header: true
- icon: linkedin
  icon_pack: fab
  link: https://linkedin.com/in/yewton
- icon: facebook
  icon_pack: fab
  link: https://facebook.com/yewton
- icon: rss
  icon_pack: fas
  link: /index.xml

  # Link to a PDF of your resume/CV from the About widget.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# - icon: cv
#   icon_pack: ai
#   link: files/cv.pdf

# Enter email to display Gravatar (if Gravatar enabled in Config)
email: "yewton@gmail.com"

# Organizational groups that you belong to (for People widget)
#   Set this to `[]` or comment out if you are not using People widget.
# user_groups:
# - Researchers
# - Visitors

birthday: "1986-06-11"

anniversary:
  -  prefix: "結婚"
     date: "2010-11-30"
     suffix: "目"
  -  prefix: "付き合って"
     date: "2007-11-30"
     suffix: "目"
  -  prefix: "社会人"
     date: "2010-04-01"
     suffix: "目"
  -  prefix: "現職勤続"
     date: "2015-09-01"
     suffix: ""
  -  prefix: "父親歴"
     date: "2016-12-09"
     suffix: ""
#+end_src

** 現在の状況

*※2022年4月18日現在*

昨今の社会情勢もあり原則リモートワーク。18時以降は基本的に父親業優先。

*** 株式会社 R

2015 年 9 月より。

テックリードやスクラムマスター等を経験しつつ、 1 年間のマネージャ経験を経て、 2022 年度より再び開発メンバーとなり、 Java や Kotlin と戯れる日々。

** 指向や価値観など

プロダクトやサービス等の開発を通じて最高のリターンを最短で得るために、自分の技術力を投資することに価値を見出す。

ソフトウェアエンジニアの中心的な価値は、実際に動く・使えるモノを、誰の手も借りず許可も得ずに作れてしまうことだと考えており、
それを武器として刃を常に研ぎ澄ませつつ、他の専門家達とも対等に意見を戦わせながら、より良いリターンを求めていきたい。

特定の技術分野に拘りはなく、必要とされているが足りていない、という部分を補っていくスタンス。
拘りはないといっても、常に /What/ に対する最高の /How/ を求めており、
また、これまでの経歴から主にサーバーサイドやインフラなどバックエンドに強みは感じている。

個人的な指向としては、複雑な現実世界を何如にシンプルにモデリングしコードに落とし込めるか、ということを考えるのが楽しいのと、
読む人間に優しいイミュータブルで簡潔な実装を好む。
その文脈で、オブジェクト指向や DDD 、クリーンアーキテクチャのような話題にも関心がある。

また、個人ではなくチームで最良の成果を引き出せることがエンジニアとして求められることだと考えているため、
チーミングや開発プロセスといった人間的な部分にも興味がある。
これまでには、 [[https://www.scrum.org/resources/online-nexus-guide][Nexus]] を用いた複数チームにおけるスクラムマスターを担ったり、
[[http://www.liberatingstructures.com/][Liberating Structures]] 等を参考にしたリモート環境下での課題設定を行う等の実践もしている。
